#!/bin/bash
### BEGIN INIT INFO
# Provides:          DeviceJson
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop anprd
### END INIT INFO
LOCKFILE=/var/lock/DeviceJson

# Start the service
start() {
        echo -n Starting DeviceJson server:

        if [ -e ${LOCKFILE} ]; then
                PID=`cat ${LOCKFILE}`
                PSOUT=`ps --no-headers $PID | wc -l`
                if [[ "$PSOUT" -eq "1" ]]; then
                        echo Process is already running.
                        exit 0
                fi

                echo Lock file exists but process is defunct.
        fi
	python /home/philro/Apps/device-json/DeviceJson.py & 
       ### Create the lock file ###
        echo $! > ${LOCKFILE}
        echo Done!
}

# Stop the service
stop() {

        if [ ! -e ${LOCKFILE} ]; then
                echo Process is not started.
        else
                PID=`cat ${LOCKFILE}`
                PSOUT=`ps --no-headers $PID | wc -l`
                if [[ "$PSOUT" -eq "1" ]]; then
                        echo -n Stopping DeviceJson server:
                        kill -2 `cat ${LOCKFILE}`
                        echo Done!
                else
                        echo Process is defunct.
                fi

                ### Now, delete the lock file ###
                rm -f ${LOCKFILE}
        fi
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        PID=`cat ${LOCKFILE}`
        PSOUT=`ps --no-headers $PID | wc -l`
        if [[ "$PSOUT" -eq "1" ]]; then
                echo DeviceJson server is running.
        else
                echo DeviceJson server is stopped.
        fi
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0
